updated workflow

diff --git a/.github/workflows/vacancy_scraper.yml b/.github/workflows/vacancy_scraper.yml
--- a/.github/workflows/vacancy_scraper.yml
+++ b/.github/workflows/vacancy_scraper.yml
@@ -1,9 +1,10 @@
+# .github/workflows/vacancy_scraper.yml
 name: Vacancy Scraper
 
 on:
   schedule:
-    - cron: '0 8 * * *'  # Run daily at 8:00 AM (Adjust as needed)
-  workflow_dispatch:     # Keep workflow_dispatch for manual triggering
+    - cron: '0 8 * * *'  
+  workflow_dispatch:     
 
 jobs:
   scrape:
@@ -27,26 +28,39 @@ jobs:
         env:
           PUPPETEER_SKIP_CHROMIUM_DOWNLOAD: true # Skip Puppeteer's automatic download
         run: |
-          # Get the latest stable Chromium version number
-          CHROMIUM_VERSION=$(curl -s https://omahaproxy.appspot.com/ | grep -Po '(?<=chromium_rel":")[^"]*')
+          # Get the latest stable Chromium version number (more reliable)
+          CHROMIUM_VERSION=$(wget -q -O - https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb | grep -Po '(?<=Version: )\d+\.\d+\.\d+\.\d+')
           echo "Installing Chromium version: $CHROMIUM_VERSION"
 
-          # Install Chromium using apt-get
+          # Install Chromium dependencies
           sudo apt-get update
-          sudo apt-get install -y chromium-$CHROMIUM_VERSION
+          sudo apt-get install -y libgbm-dev libasound2 libnss3 libxi6 libatk1.0-0 libcups2 libdbus-1-3 libexpat1 libfontconfig1 libgcc1 libgconf-2-4 libgdk-pixbuf2.0-0 libglib2.0-0 libgtk-3-0 libnspr4 libpango-1.0-0 libx11-6 libx11-xcb1 libxcb1 libxcomposite1 libxcursor1 libxdamage1 libxext6 libxfixes3 libxi6 libxrandr2 libxrender1 libxss1 libxtst6 ca-certificates fonts-liberation fonts-noto-cjk libappindicator1 libxss1 lsb-release xdg-utils wget
 
+          # Download the Chromium .deb package
+          wget https://dl.google.com/linux/direct/google-chrome-stable_current_amd64.deb
+
+          # Install the Chromium .deb package
+          sudo dpkg -i google-chrome-stable_current_amd64.deb
+
+          # Check for installation errors
+          if [ $? -ne 0 ]; then
+            echo "Error installing Chromium. Trying to fix dependencies..."
+            sudo apt-get install -f -y
+            sudo dpkg -i google-chrome-stable_current_amd64.deb
+          fi
       - name: Run the scraper
         env:
           PUPPETEER_EXECUTABLE_PATH: /usr/bin/chromium-browser # Set the path to Chromium
-        run: node vacancy_scraper.js
+        run: node vacancy_scraper.mjs
 
       - uses: actions/upload-artifact@v4
         with:
           name: vacancies
           path: vacancies.csv
 
-      - uses: actions/upload-artifact@v4
+      - uses: actions/upload-artifact@v3
         if: failure()
         with:
           name: error-screenshot
           path: error_screenshot.png
+
